project 'Psych Check.xcodeproj'
use_frameworks!
target 'Psych Check' do
	pod 'Firebase/Core'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Messaging'
  pod 'GoogleSignIn'
  pod 'TKSubmitTransitionSwift3'
  pod 'EZSwiftExtensions'
  pod 'AnimatedTextInput'
  pod 'AlertOnboarding'
  pod 'BorderedButton'
end
